# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-speexdsp, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-speexdsp
    version: 1.2rc3
source:
    md5: 4a647dfe33940b385d193af0f6d1b97e
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-speexdsp-1.2rc3-2.src.tar.gz
build:
    number: '3'
    string: '3'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-gcc-libs
about:
    home: http://www.speex.org/
    license: BSD
    summary: DSP library derived from Speex (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: f2e6ef95c370ec58e4d3ff685440bd66
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-speexdsp
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-speexdsp-1.2rc3-2-any.pkg.tar.xz
        win-64:
            md5: e1f7c35dc821e41cf28b5e419b9b675b
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-speexdsp
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-speexdsp-1.2rc3-2-any.pkg.tar.xz
