# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2w64-flac, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2w64-flac
    version: 1.3.1
source:
    md5: 3a87b0ebbc89aea7c4f32dfd16a984be
    url: http://msys2-sources.continuum.io/msys2-sources/mingw/sources/mingw-w64-flac-1.3.1-2.src.tar.gz
build:
    number: '3'
    string: '3'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2w64-libogg
        - m2w64-gcc-libs
about:
    home: http://flac.sourceforge.net/
    license: custom:Xiph, LGPL, GPL, FDL
    summary: Free Lossless Audio Codec (mingw-w64)
extra:
    msys2-binaries:
        win-32:
            md5: cf8a74dc83305883c45a451d5ea50c1f
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw32
            srcpkg: mingw32/mingw-w64-i686-flac
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/i686/mingw-w64-i686-flac-1.3.1-2-any.pkg.tar.xz
        win-64:
            md5: 47ff59b59e9588422384b43252e9c8df
            mv-dsts:
                - Library/mingw-w64
            mv-srcs:
                - mingw64
            srcpkg: mingw64/mingw-w64-x86_64-flac
            url: http://msys2-sources.continuum.io/msys2-sources/mingw/x86_64/mingw-w64-x86_64-flac-1.3.1-2-any.pkg.tar.xz
