# This file created by conda-build 3.17.8+192.g63b1f0b9
# meta.yaml template originally from:
# C:\ktietz_bld\aggregateR\r-bit64-feedstock\recipe, last modified Wed May 15 03:56:30 2019
# ------------------------------------------------

package:
    name: r-bit64
    version: '0.9_7'
source:
    sha256: 7b9aaa7f971198728c3629f9ba1a1b24d53db5c7e459498b0fdf86bbd3dff61f
    url:
        - https://cran.r-project.org/src/contrib/Archive/bit64/bit64_0.9-7.tar.gz
        - https://cran.r-project.org/src/contrib/bit64_0.9-7.tar.gz
build:
    merge_build_host: true
    number: '0'
    rpaths:
        - lib/
        - lib/R/lib/
    string: r36h6115d3f_0
requirements:
    build:
        - m2-bash 4.3.042 5
        - m2-coreutils 8.25 102
        - m2-filesystem 2016.04 4
        - m2-gcc-libs 5.3.0 4
        - m2-gmp 6.1.0 3
        - m2-libbz2 1.0.6 3
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-make 4.1 5
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-sed 4.2.2 3
        - m2-zip 3.0 2
        - m2w64-binutils 2.25.1 5
        - m2w64-bzip2 1.0.6 6
        - m2w64-crt-git 5.0.0.4636.2595836 2
        - m2w64-gcc 5.3.0 6
        - m2w64-gcc-ada 5.3.0 6
        - m2w64-gcc-fortran 5.3.0 6
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gcc-objc 5.3.0 6
        - m2w64-gmp 6.1.0 2
        - m2w64-headers-git 5.0.0.4636.c0ad18a 2
        - m2w64-isl 0.16.1 2
        - m2w64-libiconv 1.14 6
        - m2w64-libmangle-git 5.0.0.4509.2e5a9a2 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-make 4.1.2351.a80a8b8 2
        - m2w64-mpc 1.0.3 3
        - m2w64-mpfr 3.1.4 4
        - m2w64-pkg-config 0.29.1 2
        - m2w64-toolchain 5.3.0 7
        - m2w64-tools-git 5.0.0.4592.90b8472 2
        - m2w64-windows-default-manifest 6.4 3
        - m2w64-winpthreads-git 5.0.0.4634.697f757 2
        - m2w64-zlib 1.2.8 10
        - msys2-conda-epoch 20160418 1
    host:
        - _r-mutex 1.0.0 anacondar_1
        - m2w64-bwidget 1.9.10 2
        - m2w64-bzip2 1.0.6 6
        - m2w64-expat 2.1.1 2
        - m2w64-fftw 3.3.4 6
        - m2w64-flac 1.3.1 3
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gettext 0.19.7 2
        - m2w64-gmp 6.1.0 2
        - m2w64-libiconv 1.14 6
        - m2w64-libjpeg-turbo 1.4.2 3
        - m2w64-libogg 1.3.2 3
        - m2w64-libpng 1.6.21 2
        - m2w64-libsndfile 1.0.26 2
        - m2w64-libtiff 4.0.6 2
        - m2w64-libvorbis 1.3.5 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-mpfr 3.1.4 4
        - m2w64-openblas 0.2.19 1
        - m2w64-pcre 8.38 2
        - m2w64-speex 1.2rc2 3
        - m2w64-speexdsp 1.2rc3 3
        - m2w64-tcl 8.6.5 3
        - m2w64-tk 8.6.5 3
        - m2w64-tktable 2.10 5
        - m2w64-wineditline 2.101 5
        - m2w64-xz 5.2.2 2
        - m2w64-zlib 1.2.8 10
        - msys2-conda-epoch 20160418 1
        - r-base 3.6.0 hf18239d_0
        - r-bit 1.1_14 r36h6115d3f_0
    run:
        - m2w64-gcc-libs
        - r-base >=3.6,<3.7.0a0
        - r-bit >=1.1_12
test:
    commands:
        - '"%R%" -e "library(''bit64'')"'
about:
    home: http://ff.r-forge.r-project.org/
    license: GPL-2
    license_family: GPL2
    license_file: c:\ktietz_bld\conda\conda-bld\r-bit64_1557953577408\_h_env/lib/R/share/licenses/GPL-2
    summary: ' Package ''bit64'' provides serializable S3 atomic 64bit (signed) integers.  These
        are useful for handling database keys and exact counting in +-2^63. WARNING:
        do not use them as replacement for 32bit integers, integer64 are not supported
        for subscripting by R-core and they have different semantics when  combined
        with double, e.g. integer64 + double => integer64.  Class integer64 can be
        used in vectors, matrices, arrays and data.frames.  Methods are available
        for coercion from and to logicals, integers, doubles,  characters and factors
        as well as many elementwise and summary functions.  Many fast algorithmic
        operations such as ''match'' and ''order'' support inter- active data exploration
        and manipulation and optionally leverage caching.'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bgruening
        - johanneskoester
        - mingwandroid
