# This file created by conda-build 3.17.8+192.g63b1f0b9
# meta.yaml template originally from:
# C:\ktietz_bld\aggregateR\r-rcpp-feedstock\recipe, last modified Wed May 15 03:58:08 2019
# ------------------------------------------------

package:
    name: r-rcpp
    version: 1.0.1
source:
    patches:
        - 0001-Add-CXX1XSTD-to-PKG_CPPFLAGS.patch
        - 0002-macOS-When-target-lt-10.9-libstdc-supports-only-some.patch
    sha256: e76de03e5db5edc760ba7372b688d3a2f34854ad2b7dcb53b31556a46dafb904
    url:
        - https://cran.r-project.org/src/contrib/Archive/Rcpp/Rcpp_1.0.1.tar.gz
        - https://cran.r-project.org/src/contrib/Rcpp_1.0.1.tar.gz
build:
    merge_build_host: true
    number: '0'
    rpaths:
        - lib/
        - lib/R/lib/
    string: r36h6115d3f_0
requirements:
    build:
        - m2-bash 4.3.042 5
        - m2-ca-certificates 20150426 103
        - m2-coreutils 8.25 102
        - m2-curl 7.47.1 3
        - m2-db 5.3.28 3
        - m2-expat 2.1.1 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gcc-libs 5.3.0 4
        - m2-gdbm 1.11 4
        - m2-git 2.8.1 2
        - m2-gmp 6.1.0 3
        - m2-gzip 1.7 2
        - m2-heimdal 1.5.3 10
        - m2-heimdal-libs 1.5.3 10
        - m2-icu 56.1 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libbz2 1.0.6 3
        - m2-libcrypt 1.3 2
        - m2-libcurl 7.47.1 3
        - m2-libdb 5.3.28 3
        - m2-libedit 3.1 20150326
        - m2-libexpat 2.1.1 2
        - m2-libffi 3.2.1 2
        - m2-libgdbm 1.11 4
        - m2-libiconv 1.14 3
        - m2-libidn 1.32 2
        - m2-libintl 0.19.7 4
        - m2-libmetalink 0.1.2 3
        - m2-libopenssl 1.0.2.g 2
        - m2-libp11-kit 0.23.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libsqlite 3.10.0.0 2
        - m2-libssh2 1.6.0 2
        - m2-libtasn1 4.7 2
        - m2-make 4.1 5
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-openssh 7.1p2 2
        - m2-openssl 1.0.2.g 2
        - m2-p11-kit 0.23.2 2
        - m2-patch 2.7.5 2
        - m2-perl 5.22.1 2
        - m2-perl-authen-sasl 2.16 3
        - m2-perl-convert-binhex 1.123 3
        - m2-perl-encode-locale 1.04 2
        - m2-perl-error 0.17024 2
        - m2-perl-file-listing 6.04 3
        - m2-perl-html-parser 3.71 4
        - m2-perl-html-tagset 3.20 3
        - m2-perl-http-cookies 6.01 3
        - m2-perl-http-daemon 6.01 3
        - m2-perl-http-date 6.02 3
        - m2-perl-http-message 6.06 3
        - m2-perl-http-negotiate 6.01 3
        - m2-perl-io-socket-ssl 2.016 2
        - m2-perl-io-stringy 2.111 2
        - m2-perl-libwww 6.13 2
        - m2-perl-lwp-mediatypes 6.02 3
        - m2-perl-mailtools 2.14 2
        - m2-perl-mime-tools 5.506 2
        - m2-perl-net-http 6.09 2
        - m2-perl-net-smtp-ssl 1.02 2
        - m2-perl-net-ssleay 1.72 2
        - m2-perl-termreadkey 2.33 2
        - m2-perl-timedate 2.30 3
        - m2-perl-uri 1.68 2
        - m2-perl-www-robotrules 6.02 3
        - m2-sed 4.2.2 3
        - m2-vim 7.4.1721 2
        - m2-zip 3.0 2
        - m2-zlib 1.2.8 4
        - m2w64-binutils 2.25.1 5
        - m2w64-bzip2 1.0.6 6
        - m2w64-crt-git 5.0.0.4636.2595836 2
        - m2w64-gcc 5.3.0 6
        - m2w64-gcc-ada 5.3.0 6
        - m2w64-gcc-fortran 5.3.0 6
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gcc-objc 5.3.0 6
        - m2w64-gmp 6.1.0 2
        - m2w64-headers-git 5.0.0.4636.c0ad18a 2
        - m2w64-isl 0.16.1 2
        - m2w64-libiconv 1.14 6
        - m2w64-libmangle-git 5.0.0.4509.2e5a9a2 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-make 4.1.2351.a80a8b8 2
        - m2w64-mpc 1.0.3 3
        - m2w64-mpfr 3.1.4 4
        - m2w64-pkg-config 0.29.1 2
        - m2w64-toolchain 5.3.0 7
        - m2w64-tools-git 5.0.0.4592.90b8472 2
        - m2w64-windows-default-manifest 6.4 3
        - m2w64-winpthreads-git 5.0.0.4634.697f757 2
        - m2w64-zlib 1.2.8 10
        - msys2-conda-epoch 20160418 1
    host:
        - _r-mutex 1.0.0 anacondar_1
        - m2w64-bwidget 1.9.10 2
        - m2w64-bzip2 1.0.6 6
        - m2w64-expat 2.1.1 2
        - m2w64-fftw 3.3.4 6
        - m2w64-flac 1.3.1 3
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gettext 0.19.7 2
        - m2w64-gmp 6.1.0 2
        - m2w64-libiconv 1.14 6
        - m2w64-libjpeg-turbo 1.4.2 3
        - m2w64-libogg 1.3.2 3
        - m2w64-libpng 1.6.21 2
        - m2w64-libsndfile 1.0.26 2
        - m2w64-libtiff 4.0.6 2
        - m2w64-libvorbis 1.3.5 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-mpfr 3.1.4 4
        - m2w64-openblas 0.2.19 1
        - m2w64-pcre 8.38 2
        - m2w64-speex 1.2rc2 3
        - m2w64-speexdsp 1.2rc3 3
        - m2w64-tcl 8.6.5 3
        - m2w64-tk 8.6.5 3
        - m2w64-tktable 2.10 5
        - m2w64-wineditline 2.101 5
        - m2w64-xz 5.2.2 2
        - m2w64-zlib 1.2.8 10
        - msys2-conda-epoch 20160418 1
        - r-base 3.6.0 hf18239d_0
    run:
        - m2w64-gcc-libs
        - r-base >=3.6,<3.7.0a0
test:
    commands:
        - '"%R%" -e "library(''Rcpp'')"'
about:
    home: http://www.rcpp.org, http://dirk.eddelbuettel.com/code/rcpp.html, https://github.com/RcppCore/Rcpp
    license: GPL (>= 2)
    license_family: GPL3
    license_file: c:\ktietz_bld\conda\conda-bld\r-rcpp_1557934038281\_h_env/lib/R/share/licenses/GPL-2
    summary: The 'Rcpp' package provides R functions as well as C++ classes which
        offer a seamless integration of R and C++. Many R data types and objects can
        be mapped back and forth to C++ equivalents which facilitates both writing
        of new code as well as easier integration of third-party libraries. Documentation
        about 'Rcpp' is provided by several vignettes included in this package, via
        the 'Rcpp Gallery' site at <http://gallery.rcpp.org>, the paper by Eddelbuettel
        and Francois (2011, <doi:10.18637/jss.v040.i08>), the book by Eddelbuettel
        (2013, <doi:10.1007/978-1-4614-6868-4>) and the paper by Eddelbuettel and
        Balamuta (2018, <doi:10.1080/00031305.2017.1375990>); see 'citation("Rcpp")'
        for details.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bgruening
        - johanneskoester
        - mingwandroid
