# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2-msys2-runtime, last modified Mon Dec 19 13:46:46 2016
# ------------------------------------------------

package:
    name: m2-msys2-runtime
    version: 2.5.0.17080.65c939c
source:
    md5: 4d735859c1c3c1603373755e482d4e6b
    url: http://msys2-sources.continuum.io/msys2-sources/msys/sources/msys2-runtime-2.5.0.17080.65c939c-1.src.tar.gz
build:
    number: '3'
    string: '3'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
about:
    home: https://sourceforge.net/projects/msys2/
    license: GPL
    summary: Posix emulation engine for Windows
extra:
    msys2-binaries:
        win-32:
            md5: 71975da31a7595be57c4d5147a1b9cbf
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/msys2-runtime
            url: http://msys2-sources.continuum.io/msys2-sources/msys/i686/msys2-runtime-2.5.0.17080.ac97025-1-i686.pkg.tar.xz
        win-64:
            md5: 0bdbfff0aba037318547d8ae4effeec3
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/msys2-runtime
            url: http://msys2-sources.continuum.io/msys2-sources/msys/x86_64/msys2-runtime-2.5.0.17080.65c939c-1-x86_64.pkg.tar.xz
