# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Dec 17 13:11:21 2018
# ------------------------------------------------

package:
    name: pydotplus
    version: 2.0.2
source:
    fn: pydotplus-2.0.2.tar.gz
    md5: 0e2fc3dbdfd846819d4cd3769cb4595b
    patches:
        - 0001-Detect-graphviz-executables-with-bat-extension.patch
    url: https://pypi.io/packages/source/p/pydotplus/pydotplus-2.0.2.tar.gz
build:
    noarch: python
    number: '2'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_2
requirements:
    host:
        - ca-certificates 2018.11.29 ha4d7672_0
        - cairo 1.14.12 h276e583_5
        - certifi 2018.11.29 py27_1000
        - expat 2.2.5 hfc679d8_2
        - fontconfig 2.13.1 h65d0f4c_0
        - freetype 2.9.1 h6debe1e_4
        - gettext 0.19.8.1 h5e8e0c9_1
        - glib 2.56.2 h464dc38_1
        - graphite2 1.3.12 hfc679d8_1
        - graphviz 2.38.0 h08bfae6_9
        - harfbuzz 1.9.0 h04dbb29_1
        - icu 58.2 hfc679d8_0
        - jpeg 9c h470a237_1
        - libffi 3.2.1 hfc679d8_5
        - libgcc-ng 7.2.0 hdf63c60_3
        - libiconv 1.15 h470a237_3
        - libpng 1.6.36 ha92aebf_0
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libtiff 4.0.10 he6b73bb_1
        - libtool 2.4.6 h470a237_2
        - libuuid 2.32.1 h470a237_2
        - libxcb 1.13 h470a237_2
        - libxml2 2.9.8 h422b904_5
        - ncurses 6.1 hfc679d8_2
        - openssl 1.0.2p h470a237_1
        - pango 1.40.14 he752989_2
        - pcre 8.41 hfc679d8_3
        - pip 18.1 py27_1000
        - pixman 0.34.0 h470a237_3
        - pthread-stubs 0.4 h470a237_1
        - pyparsing 2.3.0 py_0
        - python 2.7.15 h33da82c_6
        - readline 7.0 haf1bffa_1
        - setuptools 40.6.3 py27_0
        - sqlite 3.26.0 hb1c47c0_0
        - tk 8.6.9 ha92aebf_0
        - wheel 0.32.3 py27_0
        - xorg-kbproto 1.0.7 h470a237_2
        - xorg-libice 1.0.9 h470a237_4
        - xorg-libsm 1.2.3 h8c8a85c_0
        - xorg-libx11 1.6.6 h470a237_0
        - xorg-libxau 1.0.8 h470a237_6
        - xorg-libxdmcp 1.1.2 h470a237_7
        - xorg-libxext 1.3.3 h470a237_4
        - xorg-libxpm 3.5.12 h470a237_2
        - xorg-libxrender 0.9.10 h470a237_2
        - xorg-libxt 1.1.5 h470a237_2
        - xorg-renderproto 0.11.1 h470a237_2
        - xorg-xextproto 7.3.0 h470a237_2
        - xorg-xproto 7.0.31 h470a237_7
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - graphviz
        - pyparsing >=2.0.1
        - python
test:
    imports:
        - pydotplus
about:
    home: http://pydotplus.readthedocs.org/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python interface to Graphviz's Dot language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chrisfilo
        - satra
