# This file created by conda-build 3.17.8+192.g63b1f0b9
# meta.yaml template originally from:
# C:\ktietz_bld\aggregateR\r-rprojroot-feedstock\recipe, last modified Wed May 15 03:58:25 2019
# ------------------------------------------------

package:
    name: r-rprojroot
    version: '1.3_2'
source:
    sha256: df5665834941d8b0e377a8810a04f98552201678300f168de5f58a587b73238b
    url:
        - https://cran.r-project.org/src/contrib/Archive/rprojroot/rprojroot_1.3-2.tar.gz
        - https://cran.r-project.org/src/contrib/rprojroot_1.3-2.tar.gz
build:
    merge_build_host: true
    noarch: generic
    number: '0'
    rpaths:
        - lib/
        - lib/R/lib/
    string: r36h6115d3f_0
requirements:
    build:
        - m2-gcc-libs 5.3.0 4
        - m2-libbz2 1.0.6 3
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-zip 3.0 2
        - msys2-conda-epoch 20160418 1
    host:
        - _r-mutex 1.0.0 anacondar_1
        - m2w64-bwidget 1.9.10 2
        - m2w64-bzip2 1.0.6 6
        - m2w64-expat 2.1.1 2
        - m2w64-fftw 3.3.4 6
        - m2w64-flac 1.3.1 3
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gettext 0.19.7 2
        - m2w64-gmp 6.1.0 2
        - m2w64-libiconv 1.14 6
        - m2w64-libjpeg-turbo 1.4.2 3
        - m2w64-libogg 1.3.2 3
        - m2w64-libpng 1.6.21 2
        - m2w64-libsndfile 1.0.26 2
        - m2w64-libtiff 4.0.6 2
        - m2w64-libvorbis 1.3.5 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-mpfr 3.1.4 4
        - m2w64-openblas 0.2.19 1
        - m2w64-pcre 8.38 2
        - m2w64-speex 1.2rc2 3
        - m2w64-speexdsp 1.2rc3 3
        - m2w64-tcl 8.6.5 3
        - m2w64-tk 8.6.5 3
        - m2w64-tktable 2.10 5
        - m2w64-wineditline 2.101 5
        - m2w64-xz 5.2.2 2
        - m2w64-zlib 1.2.8 10
        - msys2-conda-epoch 20160418 1
        - r-backports 1.1.4 r36h6115d3f_0
        - r-base 3.6.0 hf18239d_0
    run:
        - r-backports
        - r-base >=3.6,<3.7.0a0
test:
    commands:
        - '"%R%" -e "library(''rprojroot'')"'
about:
    home: https://github.com/krlmlr/rprojroot, https://krlmlr.github.io/rprojroot
    license: GPL-3
    license_family: GPL3
    license_file: c:\ktietz_bld\conda\conda-bld\r-rprojroot_1557955316377\_h_env/lib/R/share/licenses/GPL-3
    summary: Robust, reliable and flexible paths to files below a project root. The
        'root' of a project is defined as a directory that matches a certain criterion,
        e.g., it contains a certain regular file.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bgruening
        - johanneskoester
        - mingwandroid
